### ISSUE TITLE
Support numeric string for collection identifiers

### ISSUE THREAD

**Issue by guillaumesasdy** [ttu/dotnet-fake-json-server#69]
If a collection has an item with _"id": "MTgwODA3MA"_ and another item with _"id": "510"_. Then _GET /api/collection/510_ will throw an exception in `DynamicController.GetItem` on the lamba method `ObjectHelper.GetFieldValue(e, _dsSettings.IdField) == id` :

> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Operator '==' cannot be applied to operands of type 'string' and 'int''

Do you think it would be interesting to support collections with such numeric string as identifiers?

Thank you very much for this library. It's very interesting, I use it for learning purposes and prototyping.

**Comment by ttu** [comment]
Thanks for the issue!

Good to know that this project has been helpful to you :)

This case should work, but as fields are handled as dynamic values, if string id-field has a string value that is a number, code will handle it as an int.

Instead of `==` comparison should be made with `Equals-method` and this case should also work. 

Do you want to make a fix for this and add a test case? If you have any questions I can try to help.

**Comment by guillaumesasdy** [comment]
Yes I would like to push the fix. It will be my first PR on GitHub.

**Comment by guillaumesasdy** [comment]
Using `Equals` rather than `==` solve one part of the issue:
* _GET /collection/310_  will return an object with an id stored as an integer, e. g. `"id": 310` in JSON
* However it does not solve the case when the object has an id stored as an integer in a string, e. g. `"id": "310"` in JSON

So I would like to add a comparison on the id as a string when relevant, see [here](https://github.com/guillaumesasdy/dotnet-fake-json-server/blob/e57e8518b81c45f5b07184caab7972cc181ad0f8/FakeServer/Common/ObjectHelper.cs#L105). Indeed a URL query parameter has no type; so it can be an integer (or boolean, or double, as far as JSON types are concerned*), **or** a string.

In addition there is no JSON data type for date. So I would like to remove the current behavior of DynamicBinder [trying to convert](https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/Common/ModelBinders.cs#L32) to DateTime. Indeed `"aDate": 10/10/2010` or `"aDate: 2010-10-10` is not valid in JSON. My problem is that [the called method ](https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/Common/ObjectHelper.cs#L173) is also used [here](https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/Common/ObjectHelper.cs#L44). But why on that line the same TryToCastValue method isn't used for casting both currentValue and valueToCompare? It would solved my problem.

Thank for your time & help.

**Comment by ttu** [comment]
Can't remember reasons for any of these, as pretty often reasons why something is used in a place X, but not in a place Y is that method is added for fixing something. Luckily Git Blame comes to the rescue :D

Would using CompareFieldValueWithId fix the original problem?

```cs
var result = _ds.GetCollection(collectionId).Find(e => ObjectHelper.GetFieldValue(e, _dsSettings.IdField) == id).FirstOrDefault();
 
var result = _ds.GetCollection(collectionId).Find(e => ObjectHelper.CompareFieldValueWithId(e, _dsSettings.IdField, id).FirstOrDefault();
```

> In addition JSON format does not define data type for dates. So I would like to remove the current behavior of DynamicBinder trying to convert to DateTime. E. g. "id": 2010-10-10 is not valid in JSON. So GET /collection/2010-10-10 should only look for an object stored with "id": "2010-10-10".

True, it is unnecessary to try to convert value to DateTime in DynamicBinder, so functionality can be changed that it won't try to convert it to DateTime. Originally it had only int and double, but because of filtering DateTime was added there.

Commit where it was added: https://github.com/ttu/dotnet-fake-json-server/commit/004bcf6b4bd6a73095b16fbb4d6123257108138c

> My problem is that the called method is also used here. But why on that line the same TryToCastValue method isn't used for casting both currentValue and valueToCompare? It would solved my problem.

What problem you are trying to solve? I think reasoning for not using the TryToCastValue has been that data should be in the correct format in the JSON, so there is no need to try to cast every string to DateTime.

It would be really helpful if you could add some test cases that would show the problem. As you might have noticed, in many cases I don't have any idea why some functionality is done in a way it is :)

Also you could add fixes in different PR's if you are going to make fix for string/int and date problems. No need to create separate issues.

**Comment by ttu** [comment]
Closed with https://github.com/ttu/dotnet-fake-json-server/commit/b46c4597f9c8ce89804c110f3c9273782bf06031
